updates.ignore = [
  { groupId = "org.scala-lang", artifactId = "scala3-library" },
  { groupId = "org.slf4j", artifactId = "slf4j-api" },
  { groupId = "ch.qos.logback", artifactId = "logback-classic" }
]
